### PR TITLE
Able to compile erlang_ale with erlang.mk

### PR DESCRIPTION
**Pull request by ethrbh**
hello, 

I have made a small changes in erlang_ale for able to compile it with erlang.mk system.  
The next files have been added:
	Makefile
	erlang.mk
	src/erlang_ale_sup.erl
	src/erlang_ale_app.erl

I tested it, and the project can be compiled with erlang.mk as expected.

Usage: 
Compile the project: make app
Make a release: make rel
Clean all changes: make clean
Compile dependencies if they are (there is no yet): make deps

br,
/Robi

### CODE REVIEW

**Comment by fhunleth** [comment]
Your patch works for me. Could you update the README.md to let people know that they can use either rebar3 or erlang.mk to build the project? I think that only running "make" needs to be documented as opposed to "make app", "make rel" and "make clean".

Also, in the examples directory, the Makefile points to the wrong ebin directory when using erlang.mk. Here's the change to make it right:

-ALE_EBIN_DIR=$(abspath $(wildcard ../_build/default/lib))/*/ebin
+REBAR3_LIB_DIR=$(abspath $(wildcard ../_build/default/lib))
+ifeq ($(strip ${REBAR3_LIB_DIR}),)
+    ALE_EBIN_DIR=$(abspath ../ebin)
+else
+    ALE_EBIN_DIR=${REBAR3_LIB_DIR}/*/ebin
+endif

Could you update your patch with that change?

Lastly, on the commit message, the standard way to do it is to have the first line be the title of the commit. e.g. "Add support for erlang.mk". The next line is blank and then a description follows. You don't need to list the files that you changed since git does that for you. In your case, your patch is pretty obvious, so I don't think that you need a description, but you can have one if you want.

**Comment by ethrbh** [comment]
hello Frank,

Thanks for your comments. I will close this pull request, than  fix my repo according to your comments, and create a new pull req.

thanks for your help,
/Robi

**Comment by fhunleth** [comment]
I didn't catch you email quick enough. You don't need to close and create a new pull request. All that you need to do is fix the code in your branch and push the changes back up to your repository on GitHub. The updates will automatically appear here. This article might be of some help: https://help.github.com/articles/using-pull-requests/. It looks like what's done is done based on the repository status that I see, so I'd start a new pull request, but next time you won't need to do that. FWIW, I've had to go through tons of revisions to pull requests that I've done before they've finally been accepted, so this is normal.

**Comment by ethrbh** [comment]
hello Frank,

Thanks for your notes about pull request, I will learn it. Basically I now what Git is, and I'm using this tool in my official work "life", but this Github is new for me. So I will learn it :-)

Btw, the new pull req. is coming soon.

br,
/Robi

**Pull request closed without merging**
