### PR TITLE
Add support for erlang.mk build tool.

### PR DESCRIPTION
**Pull request by ethrbh**
- Makefile and erlang.mk files have been added
    - Necessary files for erlang.mk has been added in src/
    - The README.md has been updated. Rebar3 and erlang.mk build tools
are mentioned as supported tools for compile the project.
    - examples/Makefile has been updated for use proper erlang_ale's
ebin folder when Erlang/ALE was compiled or rebar3 or erlang.mk.

### CODE REVIEW

**Comment by ethrbh** [comment]
hello,

I will close this pull request, because I will add more new features. I try re-trigger a new pull request when I will be ready.

br,
/Robi

**Comment by fhunleth** [comment]
Hi Robi,

Could you open a pull request for each change? The idea is to have one pull request for one cohesive change. For example, this pull request is for erlang.mk support so anything that's not related to erlang.mk shouldn't be included. It makes it easier to review. I also suspect that merging erlang.mk support in won't be controversial. Merging in support for a particular chip, like the IO expander, will be since we should think about how we want to include individual chip support in the core Erlang/ALE repo. Supporting lots of chips could get out of hand since there are thousands of chips. 

Also, just so that you don't feel like we've been ignoring you, neither Josh nor I received updates from GitHub as you were making these changes. GitHub apparently doesn't notify on updates to pull requests that don't come with comments.

Frank

**Comment by ethrbh** [comment]
hello Frank,

Just shortly lets have a question. Can I do make separated pull requests per each commit, or do I need create more branches? Just because when the pull req. was opened, and I pushed my changes, these changes were seen in the pull req. too. And right now I have lots of push in my forked repo, and if I open a "simple pull req." all these changes will be appear for you, what you wont be, I guess. I hope tried find the way how to create pull req, for commits, but not the full repo, but I can't. Maybe I did something wrong, I don't know.

So that is why you did not reviewed my changes yet. Never mind, this can be fixed, I hope :-)

I agree with you that add support for more and more chips into ALE is not the best way. Maybe better if we can have a separated project for the chips, where ALE can be a dependency project. What do you think about it?

thanks for your help,
/Robi

**Comment by fhunleth** [comment]
My workflow is to create a branch per feature. Since I don't want to wait on the upstream maintainers to merge my pull requests, I usually have another branch for my work. I've gotten used to rebasing my branches and cherry-picking the changes that I need. It was painful for me to convert to this workflow, but when you're working with people who maintain open-source repositories in their free time, it's necessary. I'm really glad that you're making these changes, though.

**Comment by ethrbh** [comment]
hello Frank,

OK, I will create branches per feature and make pull requests on each. But first I would like finalize support for MCP7940n RTC device, I'm almost there. Than I will make sep. branches for each "major" features.

Thanks for your help and time.

br,
/Robi

**Comment by ethrbh** [comment]
hello Frank,

Now I have raised two pull requests. Please take a look at these and merge if all looks fine. The two others what are depends of these are ready to pull, but first it would be good to decide that the "chip" support features can be merged into ALE or separated project should have for these.

thanks,
/Robi

**Comment by fhunleth** [comment]
I actually don't have access to merge PRs. We'll have to wait for Josh or Torben. Both of them are at ElixirConfEU, so hopefully they'll get a chance.

**Comment by ethrbh** [comment]
hello Frank,
Thanks for your update. And let me have a question about the "chip support". Should I make a pull requests for those or do I need create a separated project in Github? What do you think about it?

thanks for your help,
/Robi

**Comment by fhunleth** [comment]
My initial reaction is to start a separate project for now due to the limited bandwidth of the maintainers of ALE. We should let people know about it in this project, though, so I'd recommend adding a section to the Erlang/ALE README.md to point to your project. This is only my opinion, though. Hopefully others will get a chance to chime in. If we don't hear from them in the next couple days, I'll ping them directly.

**Comment by ethrbh** [comment]
hello,

Yes, this also can be a solution. Of course, lets wait for couple of days.

thanks,
/Robi

**Pull request closed without merging**
